vpshosts:
  hosts:
    gateway01:
      ansible_host: 172.28.179.210
      ansible_user: sh4d0w
      ansible_become_pass: "{{ vpn_host_sudo }}"

ubuntu:
  hosts:
    gateway01:

vpn:
  hosts:
    gateway01:
      ansible_connection: local
